[package]
authors = ["Michael Leonhard <michael@leonhardllc.com>"]
categories = ["network-programming"]
description = "Derive macro for the `jtoo` crate"
edition = "2021"
keywords = ["jtoo", "htoo", "json"]
license = "MIT OR Apache-2.0"
name = "jtoo_derive"
repository = "https://github.com/mleonhard/jtoo-rs"
version = "0.1.0"

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
jtoo_derive_impl = { version = "0.1", path = "../jtoo_derive_impl" }
proc-macro2 = "1"
syn = "2.0.71"
